name: 'selene-linter'
description: 'GitHub action to run Selene, a blazing-fast modern Lua linter written in Rust'
author: 'NTBBloodbath'
branding:
  icon: check-circle
  color: blue
inputs:
  token:
    description: 'The GITHUB_SECRET token'
    required: true
  args:
    description: 'CLI arguments to pass to Selene'
    required: true
  version:
    description: 'The version of Selene to use'
runs:
  using: 'node12'
  main: 'dist/index.js'
